### ISSUE TITLE
Fix CLI bug: NaN error found. NaN error already in baseline.

### ISSUE THREAD

**Issue by wdoug** [TimMikeladze/tsc-baseline#21]
After the latest change, when running `tsc-baseline check` the CLI outputs `NaN error found. NaN error already in baseline.` at the end of each run.

<img width="340" alt="Screen Shot 2024-06-04 at 1 54 54 PM" src="https://github.com/TimMikeladze/tsc-baseline/assets/5432102/1a99c120-5946-44bd-a46c-bd1f13ed9028">

Here's a demo repo for seeing the issue: https://github.com/wdoug/tsc-baseline-demo

I dug into this a little bit and realized it is a bug with the compilation. This code:
```ts
export const getTotalErrorsCount = (errorMap: Map<string, ErrorInfo>): number =>
  [...errorMap.values()].reduce((sum, info) => sum + info.count, 0)
```
Is being compiled (in the output `dist/cli.module.js` file) into:
```js
p=function(e){return[].concat(e.values()).reduce(function(e,r){return e+r.count}
```
This is wrong. It seems like it is assuming the call to `values()` on the errorMap is returning an array, but actually that returns an iterator.

For example:
```js
const m = new Map();
const result = [].concat(m.values())
// result is: [MapIterator]
```

Hopefully just updating whatever library is doing the compilation here should fix this.

**Comment by BrianBasor** [comment]
Thanks for writing this up @wdoug .  I was seeing this little bug too.

And while I'm writing, thanks so much for fixing up the baseline logic to ignore the line and column numbers.  Excellent move, and sure makes this package more useful for me.  Ditto for the nonzero exit code when there are new errors.

I'll put in a PR with the fix for this.  It's pretty sweet that @TimMikeladze appreciated your other PRs and got them merged in.  Thanks Tim!
